### ISSUE TITLE
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/nodent-runtime/dist/index.js' when trying to install globally

### ISSUE THREAD

**Issue by lopugit** [MatAtBread/nodent-runtime#5]
When I try to install this package globally with ```sudo npm i -g nodent-runtime``` I get this error, any reason why?

**Comment by matAtWork** [comment]
This is a feature of npm that won't execute build scripts if you are root without explicit permission. Try:
```
sudo npm i -g --unsafe-perm nodent-runtime
```
